import { tool } from 'ai';
import z from 'zod';

export const DATABRICKS_TOOL_CALL_ID = 'databricks-tool-call';

export const DATABRICKS_TOOL_DEFINITION = tool({
  name: DATABRICKS_TOOL_CALL_ID,
  description: 'Databricks tool call',
  // The input schema is dynamic since its generated by the model
  inputSchema: z.any(),
  // The function is executed on Databricks
  execute: () => null,
});
