import { streamCache } from '@/lib/stream-cache';
import { UI_MESSAGE_STREAM_HEADERS } from 'ai';

/**
 * GET /api/chat/[id]/stream
 *
 * Subscribe to an active stream for a chat. This endpoint is called by the client's
 * `resume` option in useChat when reconnecting after a timeout or page reload.
 *
 * Uses a pub/sub pattern where multiple clients can subscribe to the same ongoing
 * stream and receive future chunks as they're generated.
 *
 * Returns:
 * - 204 No Content: If no active stream exists for this chat
 * - 200 with stream: If an active stream is found, returns a live subscription
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: chatId } = await params;

  console.log(`[Stream Resume] GET request for chat ${chatId}`);

  // Check if there's an active stream for this chat
  const streamId = streamCache.getActiveStreamId(chatId);

  if (!streamId) {
    console.log(`[Stream Resume] No active stream for chat ${chatId}`);
    return new Response(null, { status: 204 });
  }

  // Subscribe to the stream - this returns a tee'd copy that will receive
  // all future chunks as they're generated by the backend
  const stream = streamCache.subscribeToStream(streamId);

  if (!stream) {
    console.log(`[Stream Resume] Stream ${streamId} not found in cache`);
    return new Response(null, { status: 204 });
  }

  console.log(`[Stream Resume] Client subscribed to live stream ${streamId}`);

  return new Response(stream, {
    status: 200,
    headers: UI_MESSAGE_STREAM_HEADERS,
  });
}